#!/bin/bash

export drivers_list=""

if [ $# -lt 2 ]; then
	exit
fi

if [ ! -e $1/INITRD.SYS ]; then 
	echo gen_initrd: File $1/INITRD.SYS not found, not creating initial ramdisk 
	exit
fi

echo Generating initial ramdisk....

directory=$1
outfile=$2

shift 2

olddir=`pwd`

for f in $*; do
	drivers_list="$drivers_list $directory/`basename $f`.o" 
done

echo $drivers_list

tar -cf $outfile $drivers_list --transform=s,.*/,,

