#!/bin/bash

export drivers_list=""

if [ $# -lt 3 ]; then
	exit
fi

directory=$1
outfile=$2

shift 2

olddir=`pwd`

for f in $*; do
	drivers_list="$drivers_list $directory/`basename $f`.o" 
done

echo $drivers_list

tar -cf $outfile $drivers_list --transform=s,.*/,,

