#define MAX_PATH	255

#define	DIR_COUNT	10

#define RUN_FOREGROUND	0
#define RUN_BACKGROUND	1


#define MAX_READ_SIZE	512

#define COMMAND_TOKEN_COUNT 		20

#define RUN_COMMAND_AND_EXIT		1
#define RUN_COMMAND_AND_CONTINUE	2
#define COMMAND_PERMENANT		4

#define COMMAND_VERSION_MAJOR		1
#define COMMAND_VERSION_MINOR		0

#define TERMINATING 			2

