#define NO_ERROR		0
#define INVALID_FUNCTION	1
#define FILE_NOT_FOUND 		2
#define	PATH_NOT_FOUND		3
#define	NO_HANDLES		4
#define ACCESS_DENIED		5
#define BAD_HANDLE 		6
#define	RESERVED_1		7
#define NO_MEM			8
#define	RESERVED_2		9
#define	RESERVED_3		0x0A
#define	BAD_DISK		0x0B
#define ACCESS_ERROR		0x0C
#define BAD_FILE		0x0D
#define	RESERVED_4		0x0E
#define	INVALID_DRIVE		0x0F
#define	DIR_HAS_FILES		0x10
#define RENAME_ACR_DRIVE	0x11
#define	END_OF_DIR		0x12
#define WRITE_PROTECT_ERROR	0x13
#define BAD_DEV			0x14
#define DRIVE_NOT_READY		0x15
#define BAD_CRC			0x17
#define FILE_EXISTS		0x18
#define DIRECTORY_FULL		0x19
#define	DISK_FULL		0x1A
#define INPUT_PAST_END		0x1B
#define DEVICE_IO_ERROR		0x1C
#define BAD_FILE		0x1D
#define BAD_EXEC		0x1E
#define DEV_EXISTS 		0x1F
#define BAD_PROCESS		0x20
#define BAD_DEVICE 		0x21
#define DEVICE_IN_USE 		0x22
#define BAD_DRIVER 		0x23
#define DRIVER_ALREADY_LOADED 	0x24
#define NO_PROCESSES		0x25
#define END_OF_FILE     	0x26
#define NO_DRIVES 		0x27
#define SEEK_PASTEND		0x28
#define CANT_CLOSE_DEVICE 	0x29
#define BAD_BLOCK		0x2A
#define FILE_ALREADY_OPEN	0x2B
#define GENERAL_FAILURE		0x2c
#define NOT_DIRECTORY		0x2d
#define NOT_IMPLEMENTED		0x2e
#define FILE_IN_USE		0x2f

#define TRUE	1
#define FALSE 0
#define NULL 0

