#define NO_ERROR		0
#define INVALID_FUNCTION	1
#define FILE_NOT_FOUND 		2
#define	PATH_NOT_FOUND		3
#define	NO_HANDLES		4
#define ACCESS_DENIED		5
#define INVALID_HANDLE 		6
#define HEAP_HEADER_CORRUPT	7
#define NO_MEM			8
#define INVALID_PARAMETER	9
#define INVALID_ADDRESS		0xA
#define	UNKNOWN_FILESYSTEM	0xB
#define ACCESS_ERROR		0xC
#define INVALID_FILE		0xD
#define INVALID_PROCESS		0xE
#define INVALID_DRIVE		0xF
#define	DIRECTORY_NOT_EMPTY	0x10
#define RENAME_ACR_DRIVE	0x11
#define	END_OF_DIRECTORY	0x12
#define WRITE_PROTECT_ERROR	0x13
#define INVALID_DEVICE		0x14
#define DRIVE_NOT_READY		0x15
#define NOT_IMPLEMENTED		0x16
#define INVALID_CRC		0x17
#define INVALID_EXECUTABLE	0x18
#define SEEK_ERROR		0x19
#define INPUT_PAST_END		0x1A
#define INVALID_BLOCK_NUMBER	0x1B
#define MODULE_ALREADY_LOADED 	0x1C
#define	READ_FAULT		0x1D
#define	WRITE_FAULT		0x1E
#define GENERAL_FAILURE		0x1F
#define SHARING_VIOLATION	0x20
#define LOCK_VIOLATION		0x21
#define FILE_IN_USE		0x22
#define END_OF_FILE		0x23
#define NOT_DEVICE		0x24
#define NOT_DIRECTORY		0x25
#define IS_DIRECTORY		0x26

#define FILE_EXISTS		0x50
#define DIR_ENTRY_CREATE_ERROR	0x52

#define LAST_ERROR_NUMBER	0x52

#define TRUE	1
#define FALSE	0

